### ISSUE TITLE
Incorrect name in macOS menubar

### ISSUE THREAD

**Issue by cbrnr** [conda-forge/mnelab-feedstock#27]
The name in the macOS menubar is not "MNELAB" but "python". Furthermore, all names inside this menu are "__main__.py" instead of MNELAB.
<img width="256" alt="Screen Shot 2020-12-23 at 13 28 25" src="https://user-images.githubusercontent.com/4377312/102996104-c1f20380-4522-11eb-99ae-68d2c749a371.png">
@hoechenberger any idea what could be wrong? `pyobjc-framework-cocoa` is installed.

**Comment by hoechenberger** [comment]
We've seen this issue before if a Qt app wasn't started via pythonw. How did you invoke MNELAB?

**Comment by cbrnr** [comment]
I tried `mnelab` and `python -m mnelab`.

**Comment by hoechenberger** [comment]
Mmh. But it **used** to work at one point in the past. I wonder when it started breaking…

**Comment by hoechenberger** [comment]
> I tried `mnelab` and `python -m mnelab`.

Can you try `pythonw -m mnelab`?

**Comment by cbrnr** [comment]
That doesn't work either. Same result.

**Comment by hoechenberger** [comment]
It appears you're on Big Sur, do you think it could have anything to do with that? Does exporting `QT_MAC_WANTS_LAYER=1` before running `mnelab` help?

**Comment by cbrnr** [comment]
Yes, I'm on Big Sur. No, exporting that doesn't help (this issue does not occur with PyQt 5.12, which is what `conda` installed). Also, everything works fine when I install everything with `pip` in my normal (i.e. Homebrew) Python environment.

**Comment by cbrnr** [comment]
@hoechenberger since you are also on macOS, can you reproduce the issue?

**Comment by cbrnr** [comment]
I found the culprit: `pyobjc-framework-cocoa` is outdated (version 6.2), but `pyobjc-core` is already available at version 7.1. macOS Big Sur requires versions >= 7.1.

There is a problem with building 7.1 (https://github.com/conda-forge/pyobjc-framework-cocoa-feedstock/pull/26) - @hoechenberger do you know what needs to be changed for the automatic build to work?

**Comment by cbrnr** [comment]
https://github.com/conda-forge/pyobjc-framework-cocoa-feedstock/pull/27

**Comment by hoechenberger** [comment]
@cbrnr Sorry, I'm only now trying to catch up with GH issues. It seems you managed to get the build of pyobjc-cocoa 7.1 to pass now?

**Comment by cbrnr** [comment]
Yes, thanks for your help, I've already updated the dependency.

**Comment by hoechenberger** [comment]
since conda-forge/pyobjc-framework-cocoa-feedstock#27 has been merged, mnelab should be rebuilt in an hour or so with a build number bump

**Comment by hoechenberger** [comment]
What I meant was that we'll have to initiate the rebuild manually ;) sorry if I wasn't clear

**Comment by cbrnr** [comment]
Ah I see. Can you do that? I tested this a couple of hours ago and everything was working (MNELAB 0.6.3).

**Comment by hoechenberger** [comment]
yes can do. I mean what I would do is update our dependencies here to pyobjc-framework-cocoa-feedstock 7.1, is that what we want?

**Comment by cbrnr** [comment]
Yes, that's what we want, but this is already getting installed for me:

```
(mnelab) ~  mamba list | grep pyobjc
pyobjc-core               7.1              py39h6e9494a_0    conda-forge
pyobjc-framework-cocoa    7.1              py39h6e9494a_0    conda-forge
```

**Comment by hoechenberger** [comment]
Yes because it installs the newest version by default I suppose, but let's make sure and set the dependency explicitly
